name: Docker-tfcenter-build

on:
  workflow_dispatch:

jobs:
  build-1: #流程1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download amd64 binary
        run: |
          mkdir -p amd64
          curl -L -o amd64/app.tar.gz "http://1025.18999666.xyz:16699/tfcenter%E3%80%90%E7%BB%84%E7%BD%91%E3%80%913.4.1-linux-x86.tar.gz"
          tar -xzvf ./amd64/app.tar.gz -C ./amd64
          ls -alh amd64

      - name: Download arm64 binary
        run: |
          mkdir -p arm64
          curl -L -o arm64/app.tar.gz "http://1025.18999666.xyz:16699/tfcenter%E3%80%90%E7%BB%84%E7%BD%91%E3%80%913.4.1-linux-arm.tar.gz"
          tar -xzvf ./arm64/app.tar.gz -C ./arm64
          ls -alh arm64
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          

          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/arm64,linux/amd64 -t haoxuan8855/tfcenter:latest --push .
          
      - name: Logout from Docker Hub
        run: docker logout
 
