name: Docker-tfcenter-build

on:
  workflow_dispatch:

jobs:
  build-1: #流程1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download amd64 binary
        run: |
          mkdir -p amd64
          curl -L -o amd64/app.tar.gz "http://xg.18999666.xyz:8088/webos/link/911014fa8a7044b688dafff7ba549b08/tfcenter-Linux-x86-3.4.2.tar"
          tar -xvf ./amd64/app.tar.gz -C ./amd64
          ls -alh amd64

      - name: Download arm64 binary
        run: |
          mkdir -p arm64
          curl -L -o arm64/app.tar.gz "http://xg.18999666.xyz:8088/webos/link/8df2f4c51e664c618a22146a7100fee8/tfcenter-Linux-arm-3.4.2.tar"
          tar -xvf ./arm64/app.tar.gz -C ./arm64
          ls -alh arm64
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          

          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/arm64,linux/amd64 -t haoxuan8855/tfcenter:latest --push .
          
      - name: Logout from Docker Hub
        run: docker logout
 
