name: Docker-tfcenter-build

on:
  workflow_dispatch:

jobs:
  build-1: #流程1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download amd64 binary
        if: ${{ matrix.platform.arch }} == 'amd64'
        run: |
          mkdir -p amd64
          curl -L -o amd64/app.tar.gz \
          "http://http://117.50.183.130:22280/share-fileManagement/tfcenter-linux-x86-v3.4.1.tar.gz?shareID=mqNbxcyzk8Yxhb5&path=%2fhome%2fsoftware%2ftf-software%2ftfcenter-service%2fv3.4.1%2ftfcenter-linux-x86-v3.4.1.tar.gz&sort=2"
          tar -xzvf ~/amd64/app.tar.gz -C ~/amd64
          ls -alh amd64

      - name: Download arm64 binary
        if: ${{ matrix.platform.arch }} == 'arm64'
        run: |
          mkdir -p arm64
          curl -L -o arm64/app.tar.gz \
          "http://117.50.183.130:22280/share-fileManagement/tfcenter-linux-arm-v3.4.1.tar.gz?shareID=mqNbxcyzk8Yxhb5&path=%2fhome%2fsoftware%2ftf-software%2ftfcenter-service%2fv3.4.1%2ftfcenter-linux-arm-v3.4.1.tar.gz&sort=2"
          tar -xzvf ~/arm64/app.tar.gz -C ~/arm64
          ls -alh arm64
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          

          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/arm64,linux/amd64 -t haoxuan8855/tfcenter:latest --push .
          
      - name: Logout from Docker Hub
        run: docker logout
 
