name: Docker-tfcenter-build

on:
  workflow_dispatch:
    inputs:
      amd64_url:
        description: 'URL for amd64 binary download'
        required: true
      arm64_url:
        description: 'URL for arm64 binary download'
        required: true
env:
  #仓库云地址 例如 registry.**.aliyuncs.com
  DOCKER_REGISTRY: "${{ secrets.DOCKER_REGISTRY }}" 
  #仓库名字 
  DOCKER_NAMESPACE: "${{ secrets.DOCKER_NAMESPACE }}"  
  #仓库账户 例如 abc@email.com
  DOCKER_REGISTRY_USER: "${{ secrets.DOCKER_REGISTRY_USER }}"
  #仓库密码 
  DOCKER_REGISTRY_PASSWORD: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

  #命名空间
  NAMESPACE: haoxuan8855
  #镜像名称
  IMAGE: tfcenter

jobs:
  build-1: #流程1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download amd64 binary
        run: |
          mkdir -p amd64
          curl -L -o amd64/app.tar.gz "${{ inputs.amd64_url }}"
          tar -xvf ./amd64/app.tar.gz -C ./amd64
          ls -alh amd64

      - name: Download arm64 binary
        run: |
          mkdir -p arm64
          curl -L -o arm64/app.tar.gz "${{ inputs.arm64_url }}"
          tar -xvf ./arm64/app.tar.gz -C ./arm64
          ls -alh arm64
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/arm64,linux/amd64 -t $NAMESPACE/$IMAGE:latest --push .
          
      - name: Logout from Docker Hub
        run: docker logout
